// Package hint renders the SQLite change log into the two human-readable
// artifacts that live under .githints/: one markdown file per source file,
// and a root CHANGES.md rollup. Both are fully derived from store.Store,
// so they are always safe to delete and regenerate.
package hint

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cjrdz/githints/internal/store"
)

const dirName = ".githints"

// escape renders a plain-text string safe for inclusion in markdown. It
// prevents HTML injection (<script>, onclick, etc.) and markdown injection
// (links, images, headings) that could be exploited when the hint markdown
// is later rendered in an MCP client's webview. The escaped text remains
// human-readable; markdown formatting from the agent is intentionally lost
// in favor of safety.
func escape(s string) string {
	replacer := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		"\\", "\\\\",
		"`", "\\`",
		"*", "\\*",
		"_", "\\_",
		"[", "\\[",
		"]", "\\]",
		"(", "\\(",
		")", "\\)",
	)
	return replacer.Replace(s)
}

// FilePath returns where the hint file for a repo-relative source path
// would live, e.g. "cmd/api/main.go" -> "<root>/.githints/cmd/api/main.go.md".
func FilePath(root, srcPath string) string {
	return filepath.Join(root, dirName, srcPath+".md")
}

// RenderFile rewrites the per-file hint markdown for one source file.
func RenderFile(st *store.Store, root, srcPath string, limit int) error {
	changes, err := st.FileHistory(srcPath, limit)
	if err != nil {
		return fmt.Errorf("load history for %s: %w", srcPath, err)
	}

	out := FilePath(root, srcPath)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}

	return os.WriteFile(out, renderFileContent(changes, srcPath), 0o644)
}

func renderFileContent(changes []store.Change, srcPath string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", srcPath)
	if len(changes) == 0 {
		b.WriteString("_no recorded changes yet_\n")
	}
	for _, c := range changes {
		fmt.Fprintf(&b, "## %s\n", formatRecordedAt(c.RecordedAt, c.CreatedAt))
		fmt.Fprintf(&b, "- source: %s", c.Source)
		if c.AgentID != "" {
			fmt.Fprintf(&b, " · agent: `%s`", c.AgentID)
		}
		if c.Branch != "" {
			fmt.Fprintf(&b, " · branch: `%s`", c.Branch)
		}
		if c.CommitHash != "" {
			fmt.Fprintf(&b, " · commit: `%s`", shortHash(c.CommitHash))
		} else {
			fmt.Fprintf(&b, " · uncommitted")
		}
		if c.DiffStat != "" {
			fmt.Fprintf(&b, " · diff: %s", c.DiffStat)
		}
		if c.ClockTamperWarning {
			fmt.Fprintf(&b, " · **CLOCK TAMPER WARNING**")
		}
		b.WriteString("\n\n")
		fmt.Fprintf(&b, "%s\n", escape(c.Summary))
		if c.Reason != "" {
			fmt.Fprintf(&b, "\n_why: %s_\n", escape(c.Reason))
		}
		b.WriteString("\n")
	}

	return []byte(b.String())
}

// RenderChangelog rewrites .githints/CHANGES.md from the most recent rows
// across the whole repo, newest first, grouped by commit.
func RenderChangelog(st *store.Store, root string, limit int) error {
	changes, err := st.RecentChanges(limit)
	if err != nil {
		return fmt.Errorf("load recent changes: %w", err)
	}

	out := filepath.Join(root, dirName, "CHANGES.md")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}

	return os.WriteFile(out, renderChangelogContent(changes), 0o644)
}

func renderChangelogContent(changes []store.Change) []byte {
	var b strings.Builder
	b.WriteString("# Changes\n\n")
	b.WriteString("_auto-generated by githints — do not edit by hand_\n\n")

	lastCommit := ""
	for _, c := range changes {
		if c.CommitHash != lastCommit {
			fmt.Fprintf(&b, "## %s\n\n", headingFor(c))
			lastCommit = c.CommitHash
		}
		fmt.Fprintf(&b, "- `%s` (%s", c.FilePath, c.Source)
		if c.AgentID != "" {
			fmt.Fprintf(&b, ", %s", c.AgentID)
		}
		if c.ClockTamperWarning {
			fmt.Fprintf(&b, " [CLOCK TAMPER WARNING]")
		}
		fmt.Fprintf(&b, "): %s\n", c.Summary)
	}

	return []byte(b.String())
}

// formatRecordedAt prefers the Go-managed Unix timestamp; falls back to the
// SQLite-created display string for legacy rows.
func formatRecordedAt(recorded int64, created string) string {
	if recorded == 0 {
		return created
	}
	return time.Unix(recorded, 0).Format(time.RFC3339)
}

func headingFor(c store.Change) string {
	when := formatRecordedAt(c.RecordedAt, c.CreatedAt)
	if c.CommitHash == "" {
		return when + " · uncommitted"
	}
	return fmt.Sprintf("%s · `%s`", when, shortHash(c.CommitHash))
}

func shortHash(h string) string {
	if len(h) > 8 {
		return h[:8]
	}
	return h
}

// VerifyRendered checks that every committed markdown file under .githints/
// matches what would be regenerated from the current store. It returns a
// slice of paths that diverged (empty slice = everything consistent). This
// catches manual edits or attacker tampering with the rendered artifacts.
func VerifyRendered(st *store.Store, root string, changelogLimit, historyLimitPerFile int) ([]string, error) {
	changes, err := st.RecentChanges(changelogLimit)
	if err != nil {
		return nil, fmt.Errorf("load recent changes: %w", err)
	}
	wantChangelog := sha256.Sum256(renderChangelogContent(changes))
	gotChangelog, err := fileSHA256(filepath.Join(root, dirName, "CHANGES.md"))
	if err != nil {
		return nil, err
	}

	var diverged []string
	if !bytes.Equal(wantChangelog[:], gotChangelog[:]) {
		diverged = append(diverged, filepath.Join(dirName, "CHANGES.md"))
	}

	files, err := st.FilesWithHistory()
	if err != nil {
		return nil, fmt.Errorf("list files with history: %w", err)
	}
	for _, f := range files {
		history, err := st.FileHistory(f, historyLimitPerFile)
		if err != nil {
			return nil, fmt.Errorf("load history for %s: %w", f, err)
		}
		want := sha256.Sum256(renderFileContent(history, f))
		got, err := fileSHA256(FilePath(root, f))
		if err != nil {
			return nil, err
		}
		if !bytes.Equal(want[:], got[:]) {
			diverged = append(diverged, FilePath(root, f))
		}
	}

	return diverged, nil
}

func fileSHA256(path string) ([sha256.Size]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			// A missing file diverges from any non-empty expected content.
			return sha256.Sum256(nil), nil
		}
		return [sha256.Size]byte{}, err
	}
	return sha256.Sum256(data), nil
}
