// Package hint renders the SQLite change log into the two human-readable
// artifacts that live under .githints/: one markdown file per source file,
// and a root CHANGES.md rollup. Both are fully derived from store.Store,
// so they are always safe to delete and regenerate.
package hint

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"githints/internal/store"
)

const dirName = ".githints"

// FilePath returns where the hint file for a repo-relative source path
// would live, e.g. "cmd/api/main.go" -> "<root>/.githints/cmd/api/main.go.md".
func FilePath(root, srcPath string) string {
	return filepath.Join(root, dirName, srcPath+".md")
}

// RenderFile rewrites the per-file hint markdown for one source file.
func RenderFile(st *store.Store, root, srcPath string, limit int) error {
	changes, err := st.FileHistory(srcPath, limit)
	if err != nil {
		return fmt.Errorf("load history for %s: %w", srcPath, err)
	}

	out := FilePath(root, srcPath)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", srcPath)
	if len(changes) == 0 {
		b.WriteString("_no recorded changes yet_\n")
	}
	for _, c := range changes {
		fmt.Fprintf(&b, "## %s\n", c.CreatedAt)
		fmt.Fprintf(&b, "- source: %s", c.Source)
		if c.CommitHash != "" {
			fmt.Fprintf(&b, " · commit: `%s`", shortHash(c.CommitHash))
		} else {
			fmt.Fprintf(&b, " · uncommitted")
		}
		if c.DiffStat != "" {
			fmt.Fprintf(&b, " · diff: %s", c.DiffStat)
		}
		b.WriteString("\n\n")
		fmt.Fprintf(&b, "%s\n", c.Summary)
		if c.Reason != "" {
			fmt.Fprintf(&b, "\n_why: %s_\n", c.Reason)
		}
		b.WriteString("\n")
	}

	return os.WriteFile(out, []byte(b.String()), 0o644)
}

// RenderChangelog rewrites .githints/CHANGES.md from the most recent rows
// across the whole repo, newest first, grouped by commit.
func RenderChangelog(st *store.Store, root string, limit int) error {
	changes, err := st.RecentChanges(limit)
	if err != nil {
		return fmt.Errorf("load recent changes: %w", err)
	}

	out := filepath.Join(root, dirName, "CHANGES.md")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Changes\n\n")
	b.WriteString("_auto-generated by githints — do not edit by hand_\n\n")

	lastCommit := ""
	for _, c := range changes {
		if c.CommitHash != lastCommit {
			fmt.Fprintf(&b, "## %s\n\n", headingFor(c))
			lastCommit = c.CommitHash
		}
		fmt.Fprintf(&b, "- `%s` (%s): %s\n", c.FilePath, c.Source, c.Summary)
	}

	return os.WriteFile(out, []byte(b.String()), 0o644)
}

func headingFor(c store.Change) string {
	if c.CommitHash == "" {
		return c.CreatedAt + " · uncommitted"
	}
	return fmt.Sprintf("%s · `%s`", c.CreatedAt, shortHash(c.CommitHash))
}

func shortHash(h string) string {
	if len(h) > 8 {
		return h[:8]
	}
	return h
}
